// No Reducer
export const PUSH = 'PUSH'

// Global Reducer
export const IS_SUBMITTING = 'IS_SUBMITTING'

// User Reducer
export const AUTHENTICATE_IS_SUBMITTING = 'AUTHENTICATE_IS_SUBMITTING'
export const AUTHENTICATE_SAGA = 'AUTHENTICATE_SAGA'
export const SET_AUTHENTICATE_ERROR = 'SET_AUTHENTICATE_ERROR'
export const CLEAR_AUTHENTICATE_ERROR = 'CLEAR_AUTHENTICATE_ERROR'
export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED'
export const SET_IS_ADMIN = 'SET_IS_ADMIN'
export const SET_FIRSTNAME = 'SET_FIRSTNAME'
export const SET_LASTNAME = 'SET_LASTNAME'
export const SET_USERNAME = 'SET_USERNAME'
export const SET_EMAIL = 'SET_EMAIL'
export const SET_ROLES = 'SET_ROLES'
export const REAUTHENTICATE = 'REAUTHENTICATE'
export const LOGOUT_IS_SUBMITTING = 'LOGOUT_IS_SUBMITTING'
export const LOGOUT = 'LOGOUT'

// Query Reducer
export const SET_QUERY_TOTAL = 'SET_QUERY_TOTAL'
export const SET_QUERY_LIMIT = 'SET_QUERY_LIMIT'
export const SET_QUERY_SKIP = 'SET_QUERY_SKIP'
export const SET_QUERY_DATA = 'SET_QUERY_DATA'
export const QUERY_FETCH = 'QUERY_FETCH'

// Sproc Reducer
export const SET_TABLE_NAME = 'SET_TABLE_NAME'
export const SET_SPROC_NAME = 'SET_SPROC_NAME'
export const SPROC200206_CREATE = 'SPROC200206_CREATE'

// Dialogs
export const OPEN_SPROC200206_DIALOG = 'OPEN_SPROC200206_DIALOG'


// Obsolete
export const SET_HOURLY_OEE_VALUES_TOTAL = 'SET_HOURLY_OEE_VALUES_TOTAL'
export const SET_HOURLY_OEE_VALUES_LIMIT = 'SET_HOURLY_OEE_VALUES_LIMIT'
export const SET_HOURLY_OEE_VALUES_SKIP = 'SET_HOURLY_OEE_VALUES_SKIP'
export const SET_HOURLY_OEE_VALUES_DATA = 'SET_HOURLY_OEE_VALUES_DATA'
export const FETCH_NEXT_HOURLY_OEE_VALUES = 'FETCH_NEXT_HOURLY_OEE_VALUES'

export const RCV_DS13318 = 'RCV_DS13318'
export const ADD_KEP13318 = 'ADD_KEP13318'  // TESTING ONLY
export const RCV_KEP13318 = 'RCV_KEP13318'
